### ISSUE TITLE
Arquitetura limpa ? 

### ISSUE THREAD

**Issue by Jenrykster** [igorOsantana/utfpr_distributed_systems_chat_api#1]
Cadê a arquitetura limpa ?

**Comment by igorOsantana** [comment]
O objetivo é manter o repositório simples para que outros integrantes do projeto que não estão familiarizados com `js` possam entender/contribuir.

**Comment by Jenrykster** [comment]
Certo, ótima iniciativa, continue com o bom trabalho de escrever código claro e conciso sem abstrações desnecessárias. 👍🏽

![code](https://github.com/igorOsantana/utfpr_distributed_systems_chat_api/assets/74738661/d8fcc26f-1082-41f0-8de6-2f827ef8447d)
